### ISSUE TITLE
Add teamId param to get deployments

### ISSUE THREAD

**Issue by DenisLaboureyras** [gianlucaparadise/strapi-plugin-vercel-deploy#1]
Hello,

Thanks for your plugin ! I tried to use it but my Vercel is in team mode, and I can't retrieve the deployments list.
I have to change the request from :
https://api.vercel.com/v6/deployments?app=<app-name>
to
https://api.vercel.com/v6/deployments?teamId=<team-id>&app=<app-name>

Is it possible to add it to the config ?

Thanks,
Denis

**Comment by gianlucaparadise** [comment]
I just released [v1.1.0](https://www.npmjs.com/package/strapi-plugin-vercel-deploy/v/1.1.0) with the teamId filter. Can you try it and let me know? Thanks!

**Comment by DenisLaboureyras** [comment]
Hello,

It works like a charm !

thanks a lot.
