### ISSUE TITLE
Error on build - vercel

### ISSUE THREAD

**Issue by root3you** [gianlucaparadise/strapi-plugin-vercel-deploy#10]
When building on vercel we are getting

```
$ strapi build
17:46:01.833 | /bin/sh: hostname: command not found
```

eventhough the build succeedes ... our issue is i have no idea what we should expect to get deployed? ... strapi or our own custom data as static files?

**Comment by gianlucaparadise** [comment]
Can you try with the latest version of the `strapi-vercel-deploy-plugin` v1.4.0?

**Comment by Mihai-github** [comment]
Still not working for me, setting up the vercel deployment still gives 404 page

**Comment by gianlucaparadise** [comment]
@Mihai-github For the 404 page, please watch https://github.com/gianlucaparadise/strapi-plugin-vercel-deploy/issues/11

@root3you Any update with the latest version?

**Comment by foresthpark** [comment]
+1

**Comment by gianlucaparadise** [comment]
Duplicate: https://github.com/gianlucaparadise/strapi-plugin-vercel-deploy/issues/11

**Comment by Nileshdcool** [comment]
did anyone resolved this issue here , issue still exisit
