### ISSUE TITLE
404: NOT_FOUND on deploy

### ISSUE THREAD

**Issue by angelxescomx08** [gianlucaparadise/strapi-plugin-vercel-deploy#11]
I have installed the plugin and deploy it on vercel but the page shows a 404, do I have to do something else? I create the web hook and the api token and set the app name

**Comment by Mihai-github** [comment]
+1

**Comment by jpbast** [comment]
This is happening to me either...

**Comment by Nick87** [comment]
Same problem here

**Comment by gianlucaparadise** [comment]
What do you see in the plugin configuration page? E.g. http://localhost:1337/admin/settings/vercel-deploy

**Comment by foresthpark** [comment]
+1

**Comment by foresthpark** [comment]
> What do you see in the plugin configuration page? E.g. http://localhost:1337/admin/settings/vercel-deploy

When I go to the plugin settings I see that the inputs are all populated but get a build error on vercel

Vercel shows the following error,
> /bin/sh: hostname: command not found

but overall the build succeeds and displays a 404 page

**Comment by gianlucaparadise** [comment]
I can't replicate this issue. Do you replicate it also without the `strapi-plugin-vercel-deploy` plugin? You can disable it following these steps:

1. Edit your `config/plugins.js` file and set `enabled: false` for `"vercel-deploy"` configs
2. Rebuild using `yarn build`
3. Re-run using `yarn start`
4. Refresh the admin console
5. Verify that Vercel Deploy is not displayed in the sidebar or in the configurations

**Comment by Xonn** [comment]
I have the same problem

I first trying to deploy my strapi app on vercel without your plugin, and getting this error in build log :
`/bin/sh: hostname: command not found`

I was hoping for a better result with your plugin but unfortunatelly not

**Comment by gianlucaparadise** [comment]
Given that you can reproduce it without the `strapi-plugin-vercel-deploy` plugin, I guess it isn't a bug for this plugin. Maybe you can try opening an issue on strapi repository?

**Comment by RayBans2111** [comment]
> I have the same problem
> 
> I first trying to deploy my strapi app on vercel without your plugin, and getting this error in build log : `/bin/sh: hostname: command not found`
> 
> I was hoping for a better result with your plugin but unfortunatelly not

Were you able to figure out what was causing your issue? I am currently stuck as well. I have a completely vanilla Strapi project with only this plugin. It will build fine on my local machine, but I get the same error message in my Vercel log.

**Comment by Nileshdcool** [comment]
same issue , are there any recent updates regarding how to deploy strapi on vercel , I kept getting issue stating hostname not found.

**Comment by AleferReinert** [comment]
Same here.
