### ISSUE TITLE
Error on Uninstall

### ISSUE THREAD

**Issue by kerns** [gianlucaparadise/strapi-plugin-vercel-deploy#14]
Cannot seem to cleanly remove this plugin running `npm run strapi uninstall strapi-plugin-vercel-deploy`

![Screenshot 2023-01-11 at 23 43 49](https://user-images.githubusercontent.com/20254/211936427-53d39392-f50d-475b-a66f-62ab3f5acf0b.png)

```
  "dependencies": {
    "@strapi/plugin-i18n": "4.5.5",
    "@strapi/plugin-users-permissions": "4.5.5",
    "@strapi/provider-upload-cloudinary": "^4.5.5",
    "@strapi/strapi": "4.5.5",
    "better-sqlite3": "7.4.6",
    "package.json": "^2.0.1",
    "pg": "^8.8.0",
    "strapi-plugin-vercel-deploy": "^1.4.0"
  },
```

**Comment by gianlucaparadise** [comment]
Apparently, the `strapi uninstall <name>` command prefixes _name_ with _@strapi/plugin-_. This means that it doesn't work with the plugins that aren't under `@strapi/` (e.g. the unofficial plugins). I opened an [issue](https://github.com/strapi/strapi/issues/15433) for investigations.

In the meantime, to uninstall the plugin you can follow these steps:

1. Run `npm remove strapi-plugin-vercel-deploy`
2. Open your `./config/plugins.js` and remove the `"vercel-deploy"` entry

**Comment by gianlucaparadise** [comment]
Closing because it isn't related to the `strapi-plugin-vercel-deploy` plugin, but I will provide update.
