### ISSUE TITLE
API token exposed in Strapi settings page

### ISSUE THREAD

**Issue by richardlindon** [gianlucaparadise/strapi-plugin-vercel-deploy#2]
Great plugin, however the API token appears to be exposed in the Strapi settings page for the plugin. 
It might also be useful to lock down the deployment page to specific users/roles as well.

**Comment by gianlucaparadise** [comment]
The token is exposed on purpose. The settings page is meant to check which configurations you are using.

I'm sorry, but I never used Strapi in a team with more than one person. Which is the best approach, in your opinion?

**Comment by richardlindon** [comment]
No worries @gianlucaparadise . The problem is the token provides full access to your teams Vercel platform API. There may be circumstances where and not all Strapi Super Admins should have full access to your team's Vercel platform. 

This is an unfortunate gap on how these tokens are controlled. Hopefully in the future Vercel adds additional granular control similar to Github personal access tokens. 

Unless I'm completely wrong and there is granular access somewhere 😆 

I think a good first step would be to not display the the full API key. If it's useful to verify the correct key is used, you could display just the first or last 4 characters. I think the only place it should be fully determined is the .env file.

Unsure how to help or suggest with implementing the roles suggestion for the Deploy page. You would be the expert there 😄  But basically you would want the plugin to be configurable within the Roles page in Strapi settings (/admin/settings/roles/1)

Hopefully that helps

**Comment by gianlucaparadise** [comment]
I released v1.3.0. In the new version of the plugin:
- The API token will not be displayed entirely
- You can decide which roles can deploy

Unfortunately the Strapi documentation doesn't explain how to hide the menu link depending on the roles. If the user doesn't have any of the specified `roles`, he/she can't see the list of the deployments, can't deploy and can't see the configurations. I'll try to improve the plugin and hide the menu link somehow.

Thank you for the suggestions!
