### ISSUE TITLE
Is posible auto deploy after create a concrete article?

### ISSUE THREAD

**Issue by rmartin177** [gianlucaparadise/strapi-plugin-vercel-deploy#4]
I have one question, if i have the plugin published in strapi for schedule a day for public an article, if i have to press the deploy button then is not really worth the another plugin because at the end i have to stay at that hour for make the deploy, so its posible add a function for autodeploy when delete/add/update any collection in the content manager? for example if in content-type i mark as autodeploy "articles" from a blog, when i publish a article the hook is activate automatic and the deploy that content, this is a key feature i think

**Comment by gianlucaparadise** [comment]
Hi! You don't need `strapi-plugin-vercel-deploy` to do what you are asking. It is already feasible using Strapi Webhooks: https://strapi.io/blog/webhooks

For example, you can:
* Create a Webhook (choose a clear name like _Vercel Build_)
* Use the Deploy Hook you set in `strapi-plugin-vercel-deploy` as Webhook Url (it should be something like `https://api.vercel.com/v1/integrations/deploy/prj_[...]`)
* Check  _APP.UTILS.DELETE_, _PUBLISH_ and _UNPUBLISH_ events for _Entry_
* Save your Webhook

Given that this feature is supported by Strapi out-of-the-box, I don't think it's ok to re-implement it in `strapi-plugin-vercel-deploy`.
