### ISSUE TITLE
Not supported in new Strapi versions

### ISSUE THREAD

**Issue by birdzai** [gianlucaparadise/strapi-plugin-vercel-deploy#8]
Not supported in new Strapi versions.

**Supported in Node Versions**
"engines": {
"node": ">=14.19.1 <=16.x.x",
"npm": ">=6.0.0"
},

**Not Supported in Latest Versions**
"engines": {
"node": ">=14.19.1 <=18.x.x",
"npm": ">=6.0.0"
},

**Comment by gianlucaparadise** [comment]
Which version of Strapi are you using?

**Comment by gianlucaparadise** [comment]
Can you try with the latest version of the `strapi-vercel-deploy-plugin` v1.4.0?

**Comment by birdzai** [comment]
Works fine 😊  Thanks.
