### ISSUE TITLE
 Module not found: Error: Can't resolve '@strapi/icons/{icon}'

### ISSUE THREAD

**Issue by YannickDurden** [gianlucaparadise/strapi-plugin-vercel-deploy#9]
Hi,

I tried to install the plugin locally with Strapi v4.5.0 but when I run `yarn develop` I've got this error:

````bash
ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/icons/ExternalLink' in 'C:\{path_to_local_strapi}\node_modules\strapi-plugin-vercel-deploy\node_modules\@strapi\design-system\dist\v2\Link'
````

To fix the problem, I found each 'strapi/icons' inside @strapi/design-system and added '.js' for each strapi/icons import.

**Comment by gianlucaparadise** [comment]
Can you try with the latest version of the `strapi-vercel-deploy-plugin` v1.4.0?

**Comment by gianlucaparadise** [comment]
Closed for missing feedback
